### ISSUE TITLE
hi, 我可以在注明出处的情况下使用你的文章么？

### ISSUE THREAD

**Issue by orca-j35** [yongxinz/tech-blog#1]
没有看到这个仓库有明确给出license，但是想在自己的笔记中引用（或演绎）你文章中的内容，希望你允许，我会注明出处的，谢谢啦大兄弟

**Comment by yongxinz** [comment]
> 没有看到这个仓库有明确给出license，但是想在自己的笔记中引用（或演绎）你文章中的内容，希望你允许，我会注明出处的，谢谢啦大兄弟

不好意思，刚看到~
可以引用的

**Comment by orca-j35** [comment]
好的，谢谢啦

**Comment by orca-j35** [comment]
可以，没问题哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月29日(星期三) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yongxinz/tech-blog] hi, 我可以在注明出处的情况下使用你的文章么？ (#1)





 
Closed #1 as completed.
